# Generated by Django 5.2 on 2025-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses_joined',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
