# Generated by Django 5.2 on 2025-05-26 07:39

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_customuser_courses_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(max_length=500, upload_to=courses.models.custom_upload_to, verbose_name='Изображение'),
        ),
    ]
